# Workflow per pubblicare il branch develop nel repository di dev

name: DEV

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.API_TOKEN_GITHUB }}
      - name: apt update
        run: sudo apt update
      - name: apt-get update
        run: sudo apt-get update -y
      - name: install sed package
        run: sudo apt-get install -y sed
      - name: install git
        run: sudo apt install git
      - name: check git version
        run: git --version
      - name: add username
        run: git config --global user.name "simonezardi"
      - name: add email
        run: git config --global user.email "simone.zardi@storci.com"
      - name: add remote
        run: git remote add dev https://$username:$repo_key@github.com/Storci/pwa-dev.git
        env:
          repo_key: ${{ secrets.API_TOKEN_GITHUB }}
          username: simonezardi
      - name: fetch repository
        run: git fetch --unshallow origin
      - name: check remote
        run: git remote -v
      - name: check branches
        run: git branch
      - name: checkout branch develop
        run: git checkout develop
      #- name: change app version on file
      #  run: sed -e 's/Version/${{ github.sha }}/' 01_Customers.html > 01_Customers.html.tmp && mv 01_Customers.html.tmp 01_Customers.html
      #- name: controlla il file modificato
      #  run: cat 01_Customers.html
      #- name: controlla lo stato del branch
      #  run: git status
      #- name: aggiunge il file modificato in stage
      #  run: git add 01_Customers.html
      #- name: controlla lo stato del branch
      #  run: git status
      #- name: commit
        #run: git commit -m "update version 01_Customers.html"
      - name: rimuove i files
        run: git rm -rf ".github"
      - name: commit
        run: git commit --amend --no-edit
      - name: push to dev repository
        run: git push https://$username:$repo_key@github.com/Storci/pwa-dev.git develop:main --force
        env:
          repo_key: ${{ secrets.API_TOKEN_GITHUB }}
          username: simonezardi
